name: Sync to GitLab

on:
  push:
    branches:
      - '**'  # Trigger for all branches
  delete:
    branches:
      - '**'  # Trigger for all branches

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set user identity
        run: |
          git config --global user.email "manjeetyadav19@gmail.com"
          git config --global user.name "manjeetyadav19"

      - name: Pull changes from GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/manjeetyadav19/docker_test1.git
          git pull gitlab main --allow-unrelated-histories --rebase  # Specify the rebase strategy

      - name: Push to GitLab
        run: |
          git push gitlab HEAD:main  # Adjust the branch name as needed
