name: Mirroring

on:
  push:
    branches:
      - '**'  # Trigger for all branches
      - '!gitlab-sync'  # Exclude the branch used for GitLab synchronization

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set user identity
        run: |
          git config --global user.email "manjeetyadav19@gmail.com"
          git config --global user.name "manjeetyadav19"

      - name: Pull changes from GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/manjeetyadav19/docker_test1.git
          git fetch gitlab --prune
          git reset --hard gitlab/main

      - name: Push changes to GitLab
        run: |
          git push gitlab HEAD:$GITHUB_REF --force
