name: Sync to GitLab

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure git merge behavior
        run: git config pull.rebase false

      - name: Pull changes from GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/manjeetyadav19/docker_test1.git
          git pull gitlab main --allow-unrelated-histories  # Adjust the branch name as needed

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/manjeetyadav19/docker_test1.git
          git push gitlab HEAD:main  # Adjust the branch name as needed
